# Generated by Django 4.2.2 on 2023-07-01 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_rename_company_code_companymodel_code_and_more'),
        ('users', '0002_alter_usermodel_first_name_alter_usermodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.companymodel'),
        ),
    ]
