# Generated by Django 4.2.2 on 2023-06-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_taskmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='image',
            field=models.ImageField(blank=True, default='no_image.png', upload_to='tasks_image/', verbose_name='Изображение'),
        ),
    ]
