# Generated by Django 4.2.2 on 2023-07-02 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='name',
            field=models.CharField(max_length=22, verbose_name='Название'),
        ),
    ]
