# Generated by Django 4.2.2 on 2023-07-02 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_rename_company_code_companymodel_code_and_more'),
        ('tasks', '0005_taskmodel_by_user_alter_taskmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.companymodel'),
        ),
    ]
