# Generated by Django 4.2.2 on 2023-07-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companymodel',
            old_name='company_code',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
