# Generated by Django 4.2.3 on 2023-07-19 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_rename_company_code_companymodel_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitleModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('add_task', models.BooleanField(verbose_name='Может добавлять задачи')),
                ('name', models.CharField(max_length=50, verbose_name='Название должности')),
            ],
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='code',
            field=models.CharField(error_messages={'unique': 'Код для вступления в компанию должен быть уникальным.'}, max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(10, 'Код компании должен быть больше 10 символов')], verbose_name='Код для вступления в компанию'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='name',
            field=models.CharField(error_messages={'unique': 'Название компании должен быть уникальным.'}, max_length=180, unique=True, verbose_name='Название компании'),
        ),
    ]
